server:
  port: 8762

spring:
  application:
    name: Service-Provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smbms?serverTimezone=UTC
    username: root
    password: ok
    
  jackson:
    data-format:yyyy-MM-dd

mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    auto-mapping-behavior: full

logging:
  level:
    com:
      zb:
        sp:
          dao: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/